### ISSUE TITLE
v2.0.0 - Roadmap

### ISSUE THREAD

**Issue by Bardo91** [mico-corp/mico#19]
Before releasing v2.0.0 there is a lot to do! The purpose of this version is to renew MICO completely, the final purpose remains the same, but there were a lot of structures and hierarchies that made not sense at all, or were obsoletes. Here there is a list of the remaining issues that are required before releaseing v2.0.0.

- [x] MPlugins should expose Blocks not VisualBlocks. https://github.com/mico-corp/mico/issues/21
- [x] VisualBlocks can be templateless and receibe the backendblock in the constructor. https://github.com/mico-corp/mico/issues/22
- [x] Move VisualBlocks and related to a separate library (Removing nodes library from flow). https://github.com/mico-corp/mico/issues/20
- [x] Auto testing blocks. https://github.com/mico-corp/mico/issues/23
~~- [ ] Create an intermediate lenguage for extra "UI" required to define blocks and then remove QT definitely~~ Delayed to 2.1.X

**Comment by Bardo91** [comment]
Prereleased in https://github.com/mico-corp/mico/releases/tag/v2.0.0-alpha
